# Documentation is available here https://github.com/actions/labeler

'type: support :books:':
  - support/**/*
  - '!support/e2e/**'
  - '!support/actions/**'
  - '!support/azure/**'
  - '!support/deprecated/**'

'type: deprecation :wastebasket:':
  - support/deprecated/**/*

'type: ci :evergreen_tree:':
  - .github/**/*
  - support/azure/**/*
  - '!.github/ISSUE_TEMPLATE/**'
  - '!.github/**/*.md'

'package: jest-prosemirror :performing_arts:':
  - packages/jest-prosemirror/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'package: jest-remirror :black_joker:':
  - packages/jest-remirror/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'package: prosemirror-suggest :bulb:':
  - packages/prosemirror-suggest/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'package: multishift :arrow_down_small:':
  - packages/multishift/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'package: remirror :purple_circle:':
  - packages/remirror/**/*.{ts,tsx,json}
  - packages/@remirror/**/*.{ts,tsx,json}
  - '!packages/@remirror/playground/**/*'
  - '!packages/@remirror/cli/**/*'
  - '!**/*.spec.{ts,tsx}'

'framework: react :atom_symbol:':
  - packages/@remirror/*react*/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'framework: dom :globe_with_meridians:':
  - packages/@remirror/*dom*/**/*.{ts,tsx,json}
  - '!**/*.spec.{ts,tsx}'

'package: @remirror/cli :pager:':
  - packages/@remirror/cli/**/*.{ts,tsx,json}

'type: playground :joystick:':
  - packages/@remirror/playground/**/*.{ts,tsx,json}
  - support/website/src/pages/playground.tsx

'type: docs :pencil:':
  - docs/**/*
  - '**/readme.md'

'type: changeset :butterfly:':
  - '.changeset/**/*'

'test: unit :white_check_mark:':
  - '**/*.spec.{ts,tsx}'

'test: e2e :heavy_check_mark:':
  - '**/*.e2e.test.{ts,tsx}'
  - packages/**/*.snap
  - support/e2e/**/*.{ts,tsx,json,snap}
