# Documentation is available here https://github.com/actions/labeler

'type: support :books:':
  - any:
      [
        'support/**/*',
        '!support/e2e/**',
        '!support/actions/**',
        '!support/azure/**',
        '!support/deprecated/**',
      ]

'type: deprecation :wastebasket:':
  - any: ['support/deprecated/**/*']

'type: ci :evergreen_tree:':
  - any: ['.github/**/*', 'support/azure/**/*', '!.github/ISSUE_TEMPLATE/**', '!.github/**/*.md']

'test: unit :white_check_mark:':
  - any: ['**/*.spec.{ts,tsx}']

'test: e2e :heavy_check_mark:':
  - any: ['**/*.e2e.test.{ts,tsx}', 'support/e2e/**/*']

'package: jest-prosemirror :performing_arts:':
  - any: ['packages/jest-prosemirror/**/*']

'package: jest-remirror :black_joker:':
  - any: ['packages/jest-remirror/**/*']

'package: prosemirror-suggest :bulb:':
  - any: ['packages/prosemirror-suggest/**/*']

'package: multishift :arrow_down_small:	':
  - any: ['packages/multishift/**/*']

'package: remirror :purple_circle:':
  - any:
      [
        'packages/remirror/**/*',
        'packages/@remirror/**/*',
        '!packages/@remirror/playground/**/*',
        '!packages/@remirror/cli/**/*',
      ]

'framework: react :atom_symbol:':
  - any: ['packages/@remirror/*react*/**/*']

'framework: dom :globe_with_meridians:':
  - any: ['packages/@remirror/*dom*/**/*']

'package: @remirror/cli :pager:':
  - any: ['packages/@remirror/cli/**/*']

'type: playground :joystick:':
  - any: ['packages/@remirror/playground/**/*', 'support/website/src/pages/playground.tsx']

'type: docs :pencil:':
  - any: ['docs/**/*', '**/readme.md']
