jobs:
  - template: support/pipelines/jobs.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-16.04'

  - template: support/pipelines/jobs.yml
    parameters:
      name: Windows
      vmImage: 'vs2017-win2016'
