parameters:
  name: '' # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
  - ${{ if eq(parameters.name, 'Linux') }}:
      - job: ${{ parameters.name }}Checks
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - template: yarn-install.yml
          - bash: |
              yarn ci:checks
            displayName: 'Run all checks'

  - ${{ if eq(parameters.name, 'Linux') }}:
      - job: ${{ parameters.name }}UnitTests
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - template: yarn-install.yml
          - bash: |
              yarn test
            displayName: 'Run unit tests'

  - job: ${{ parameters.name }}IntegrationTests
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - template: yarn-install.yml
      - bash: |
          yarn build
          yarn test:puppeteer
        displayName: 'Run integration tests'
