version: '3.7'
services:
  puppeteer-linux:
    environment:
      REMIRROR_E2E_DOCKER: 'true'
      CI: 'true'
    build:
      dockerfile: ./support/docker/puppeteer-linux-dev.Dockerfile
      context: ../../
    volumes:
      - type: bind
        source: ../../e2e
        target: /remirror/e2e
        volume:
          nocopy: false
    command: 'yarn test:e2e'

  puppeteer-windows:
    environment:
      REMIRROR_E2E_DOCKER: 'true'
    build:
      dockerfile: ./support/docker/puppeteer-windows.Dockerfile
      context: ../../
    volumes:
      - type: bind
        source: ../../e2e
        target: /remirror/e2e
        volume:
          nocopy: false
    command: 'yarn test:e2e'
