name: 'publish-prs'
description: 'Publish a pull request by adding \"/publish\" as a comment'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  giphyKey:
    required: false
    description: 'api key for giphy comments'
  version:
    required: false
    description: 'command to run which updates the versions of all packages'
  build:
    required: true
    description: 'the command to build all packages after versioning is completed'
runs:
  using: 'node12'
  main: 'dist/actions-pr.cjs.js'
