name: Node CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: audit dependencies
        run: yarn audit

      - name: install dependencies
        run: yarn ci

      - name: lint files
        run: yarn lint

      - name: typecheck project
        run: yarn typecheck

      - name: run unit tests & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        if: github.ref == 'refs/heads/canary'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true

      - name: run unit tests
        if: github.ref != 'refs/heads/canary'
        run: yarn test

      - name: build project
        run: yarn build

      - name: check sizes
        run: yarn size

      - name: integration tests
        run: yarn test:e2e

      - name: create release pr or publish to npm
        if: github.ref == 'refs/heads/canary'
        uses: changesets/action@master
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
