name: Node CI

on:
  push:
    branches:
      - main
      - next
      - changeset-release/main
      - changeset-release/next
  pull_request:
    branches:
      - main
      - next

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Release the project if everything else passes
  release:
    timeout-minutes: 15
    needs: [lint, typecheck, unit_test, build_test, size_check, chromium_e2e, firefox_e2e]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'

    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: create release pr or publish to npm
        uses: changesets/action@master
        with:
          fetch-depth: 0
          publish: pnpm run release
          version: pnpm run ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Lint the project
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: lint files
        run: pnpm run lint

  # Typecheck the project
  typecheck:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: typecheck project
        run: pnpm run typecheck

  # Unit test and update coverage report
  unit_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: run unit tests
        run: pnpm run test

      - name: publish code coverage report
        uses: paambaati/codeclimate-action@v2.4.0
        if: github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: 'echo Coverage'
          debug: false

  # Build the project and run tests on built files.
  build_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: run unit tests
        run: pnpm run test:build

  # Check that sizes are within their boundaries
  size_check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: check sizes
        run: pnpm run size

  # Run chromium e2e tests with playwright
  chromium_e2e:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: npm install pnpm -g

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: chrome integration test ${{ matrix.os }}
        run: cd support/e2e && pnpm run chromium

  # Run firefox e2e tests with playwright
  firefox_e2e:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: npm install pnpm -g

      - name: audit dependencies
        run: pnpm run audit

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: firefox integration test ${{ matrix.os }}
        run: cd support/e2e && pnpm run firefox
