name: Deploy Docs

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - next

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy_docs:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request

    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm audit --audit-level high

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: build docs
        run: pnpm run build:docs

      - name: deploy docs
        uses: nwtgck/actions-netlify@develop
        with:
          publish-dir: './support/website/build'
          production-branch: next
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy Docs from GitHub Actions - ${{ github.event.pull_request.title || github.ref }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NEXT_NETLIFY_SITE_ID }}
