name: docs

on:
  push:
    branches:
      - beta
  pull_request:
    types: [opened, synchronize]
    branches:
      - beta

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy_docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    # don't run this job from a fork repository
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          # Uses node 14 to allow nullish coalescing in `.js` files
          node-version: 14

      - name: install and audit
        uses: ./support/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build docs
        run: pnpm build:docs

      - name: deploy docs
        uses: nwtgck/actions-netlify@develop
        with:
          publish-dir: './website/build'
          production-branch: beta
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy Docs from GitHub Actions - ${{ github.event.pull_request.title || github.ref }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NEXT_NETLIFY_SITE_ID }}
