name: E2E Tests

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: checkout code repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: audit dependencies
        run: pnpm audit --audit-level high

      - name: install dependencies
        run: pnpm install

      - name: build project
        run: pnpm run build

      - name: chrome integration test ${{ matrix.os }}
        run: cd e2e && pnpm run chromium

      - name: webkit integration test ${{ matrix.os }}
        run: cd e2e && pnpm run webkit
